# Generated by Django 5.1.6 on 2025-03-08 01:26

import django.core.validators
import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_class_alter_section_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True, verbose_name='Admission Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_of_admission', models.DateField(verbose_name='Date of Admission')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Other', 'Other')], max_length=20, verbose_name='Religion')),
                ('caste_category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20, verbose_name='Caste Category')),
                ('address', models.TextField(verbose_name='Address')),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits.', regex='^[0-9]{10}$')], verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='Blood Group')),
                ('student_image', models.ImageField(upload_to='students/images/', verbose_name='Student Image')),
                ('aadhar_card', models.FileField(upload_to='students/documents/', verbose_name='Aadhar Card')),
                ('transfer_certificate', models.FileField(upload_to='students/documents/', verbose_name='Transfer Certificate')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.class', verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('student', models.ForeignKey(blank=True, default=students.models.get_default_student, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
