# Generated by Django 5.1.6 on 2025-03-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/teacher_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='uploads/teacher_resumes/')),
                ('joining_letter', models.FileField(blank=True, null=True, upload_to='uploads/teacher_joining_letters/')),
            ],
        ),
    ]
