# Generated by Django 5.1.6 on 2025-03-07 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('section', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.class'),
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
    ]
