# Generated by Django 5.1.6 on 2025-03-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('principal_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('academic_calendar', models.FileField(blank=True, null=True, upload_to='calendar/')),
            ],
        ),
    ]
