# Generated by Django 5.1.6 on 2025-03-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='academic_calendar',
            field=models.FileField(blank=True, null=True, upload_to='calendar/', verbose_name='अकादमिक सेशन कैलेण्डर'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='address',
            field=models.TextField(verbose_name='पता'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ईमेल'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='logo',
            field=models.ImageField(upload_to='logos/', verbose_name='स्कूल लोगो'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='mobile',
            field=models.CharField(max_length=15, unique=True, verbose_name='मोबाइल नंबर'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='principal_name',
            field=models.CharField(max_length=255, verbose_name='प्रधानाचार्य का नाम'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='registration_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='रजिस्ट्रेशन नंबर'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.CharField(max_length=255, verbose_name='स्कूल का नाम'),
        ),
    ]
