# Generated by Django 5.1.6 on 2025-03-06 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0002_alter_schoolprofile_academic_calendar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='academic_calendar',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/school_logos/'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='principal_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.CharField(max_length=255),
        ),
    ]
