# Generated by Django 5.1.6 on 2025-03-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0003_remove_schoolprofile_academic_calendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='start_date',
            field=models.DateField(),
        ),
    ]
